=== tonyprod97/Open_Computing-6th_semester/laboratory/Open_Computing-6th_semester/data-ns/gramatika.dtd
<!-- crkva DTD definicija -->

<!ELEMENT crkva (naziv,zupnik,zupni_ured,adresa,misa+,god_osnutka?,max_kapacitet?,zbor?)>
<!ATTLIST crkva kategorija (katolicka|pravoslavna|protestantska) #REQUIRED>
<!ATTLIST crkva aktivnosti (Vjeronauk|Ministriranje|Caritas|Zaruke) #IMPLIED>
<!-- naziv -->
<!ELEMENT naziv (#PCDATA)>
<!--zupnik-->
<!ELEMENT zupnik (ime,prezime,telefon*)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ATTLIST telefon tip (mobilni|fiksni|telefaks) #IMPLIED>
<!ATTLIST telefon br_mreze (099|098|095|092|091|01) #REQUIRED>
<!-- zupni_ured -->
<!ELEMENT zupni_ured (mail?,telefon)>
<!ATTLIST zupni_ured xmlns:zu CDATA #FIXED "http://hrvatske-crkve/zupni_ured">
<!ELEMENT mail (#PCDATA)>
<!-- 
<!ELEMENT telefon (#PCDATA)>
<!ATTLIST telefon tip (mobilni|fiksni|telefaks) #IMPLIED>
<!ATTLIST telefon br_mreze (099|098|095|092|091|01) #REQUIRED>
 -->
<!-- adresa -->
<!ELEMENT adresa (mjesto,ulica?)>
<!ELEMENT mjesto (#PCDATA)>
<!ATTLIST mjesto pos_broj CDATA #REQUIRED>
<!ELEMENT ulica (#PCDATA)>
<!ATTLIST ulica kuc_broj CDATA #IMPLIED>
<!--misa-->
<!ELEMENT misa (datum,vrijeme)>
<!ATTLIST misa ispovijed (Prije|Poslije) #IMPLIED>
<!ELEMENT datum (#PCDATA)>
<!ELEMENT vrijeme (#PCDATA)>
<!-- god_osnutka -->
<!ELEMENT god_osnutka (#PCDATA)>
<!-- max_kapacitet -->
<!ELEMENT max_kapacitet (#PCDATA)>
<!-- zbor -->
<!ELEMENT zbor (naziv,broj?)>
<!--!ELEMENT naziv (#PCDATA)> -->
<!ELEMENT broj (#PCDATA)>

=== tonyprod97/Open_Computing-6th_semester/laboratory/Open_Computing-6th_semester/data-ns/podaci.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE crkva SYSTEM "./gramatika.dtd">
<crkva kategorija="katolicka" aktivnosti="Ministriranje">
    <naziv>Zagrebačka katedrala</naziv>
    <zupnik>
        <ime>Ivan</ime>
        <prezime>Ivanić</prezime>
        <telefon tip="mobilni" br_mreze="099">9998989</telefon>
    </zupnik>
    <zu:zupni_ured xmlns:zu="http://hrvatske-crkve/zupni_ured">
        <zu:mail>tiskovni@zg-nadbiskupija.hr</zu:mail>
        <zu:telefon tip="fiksni" br_mreze="0">14894878</zu:telefon>
    </zu:zupni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
        <ulica kuc_broj="31">Kaptol</ulica>
    </adresa>
    <misa ispovijed="Prije Poslije">
        <datum>2019-04-07</datum>
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa ispovijed="Prije Poslije">
        <datum>2019-04-14</datum>
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa ispovijed="Prije Poslije">
        <datum>2019-04-21</datum>
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1094</god_osnutka>
    <max_kapacitet>1500</max_kapacitet>
    <zbor>
        <naziv>Slavuji Katedrale Zagreb</naziv>
    </zbor>
</crkva>

<crkva kategorija="katolicka" aktivnosti="Zaruke Caritas">
    <naziv>Dubrovačka katedrala</naziv>
    <zupnik>
        <ime>Vlaho</ime>
        <prezime>Katušić</prezime>
        <telefon tip="mobilni" br_mreze="091">8798529</telefon>
    </zupnik>
    <zu:zupni_ured xmlns:zu="http://hrvatske-crkve/zupni_ured">
        <zu:mail>dubrovnik.katedrala@info.hr</zu:mail>
        <zu:telefon tip="fiksni" br_mreze="0">20312011</zu:telefon>
    </zu:zupni_ured>
    <adresa>
        <mjesto pos_broj="20000">Dubrovnik</mjesto>
        <ulica kuc_broj="5">Brsalje</ulica>
    </adresa>
        <misa ispovijed="Prije">
        <datum>2019-05-07</datum>
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa ispovijed="Prije">
        <datum>2019-05-14</datum>
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa ispovijed="Prije">
        <datum>2019-05-21</datum>
        <vrijeme>11:00</vrijeme>
    </misa>

    <god_osnutka>1713</god_osnutka>
    <max_kapacitet>500</max_kapacitet>
    <zbor>
        <naziv>Zbor sv. Vlaha</naziv>
    </zbor>
</crkva>

<crkva kategorija="katolicka" aktivnost="Caritas Zaruke Ministriranje">
    <naziv>Katedrala Svetog Vida</naziv>
    <zupnik>
        <ime>Mihovil</ime>
        <prezime>Radić</prezime>
        <telefon tip="mobilni" br_mreze="092">14568875</telefon>
    </zupnik>
    <zu:zupni_ured xmlns:zu="http://hrvatske-crkve/zupni_ured">
        <zu:mail>zupa-vido@email.t-com.hr</zu:mail>
    </zu:zupni_ured>
    <adresa>
        <mjesto pos_broj="51000">Rijeka</mjesto>
        <ulica kuc_broj="2">Trg Svete Barbare</ulica>
    </adresa>
    <misa>
        <datum>2019-05-07</datum>
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa ispovijed="Prije Poslije">
        <datum>2019-04-22</datum>
        <vrijeme>19:00</vrijeme>
    </misa>
    <misa ispovijed="Prije Poslije">
        <datum>2019-05-21</datum>
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1638</god_osnutka>
    <max_kapacitet>300</max_kapacitet>
    <zbor>
        <naziv>Vidova Dica</naziv>
        <broj>27</broj>
    </zbor>
</crkva>

<crkva kategorija="pravoslavna">
   <naziv>Preobraženja gospodnjeg</naziv>
    <zupnik>
        <ime>Bogdan</ime>
        <prezime>Malik</prezime>
        <telefon tip="mobilni" br_mreze="098">9479100</telefon>
    </zupnik>
    <zu:zupni_ured xmlns:zu="http://hrvatske-crkve/zupni_ured">
        <zu:telefon tip="fiksni" br_mreze="0">14614132</zu:telefon>
    </zu:zupni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
    </adresa>
     <misa>
        <datum>2019-05-07</datum>
        <vrijeme>06:00</vrijeme>
    </misa>
    <misa>
        <datum>2019-04-22</datum>
        <vrijeme>17:00</vrijeme>
    </misa>
    <misa>
        <datum>2019-08-21</datum>
        <vrijeme>10:00</vrijeme>
    </misa>
    <god_osnutka>1866</god_osnutka>
    <max_kapacitet>100</max_kapacitet>
</crkva>

<crkva kategorija="katolicka" aktivnosti="Vjeronauk">
    <naziv>Crkva Gospe od Betlema</naziv>
    <zupnik>
        <ime>Marko</ime>
        <prezime>Šoltarić</prezime>
        <telefon tip="mobilni" br_mreze="098">8571289</telefon>
    </zupnik>
    <zu:zupni_ured xmlns:zu="http://hrvatske-crkve/zupni_ured">
        <zu:mail>zupni-ured@sveti-petar.hr</zu:mail>
        <zu:telefon tip="fiksni" br_mreze="0">14633534</zu:telefon>
    </zu:zupni_ured>
    <adresa>
        <mjesto pos_broj="21000">Split</mjesto>
        <ulica kuc_broj="3">Marangunićevo šetalište</ulica>
    </adresa>
    <misa ispovijed="Poslije">
        <datum>2019-07-12</datum>
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa ispovijed="Poslije">
        <datum>2019-07-02</datum>
        <vrijeme>19:00</vrijeme>
    </misa>
    <misa ispovijed="Poslije">
        <datum>2019-04-21</datum>
        <vrijeme>18:00</vrijeme>
    </misa>
    <god_osnutka>1500</god_osnutka>
</crkva>
