=== tonyprod97/Open_Computing-6th_semester/laboratory/Open_Computing-6th_semester/gramatika.dtd
<!-- crkva DTD definicija -->
<!ELEMENT podaci (crkva+)>
<!ELEMENT crkva (naziv,župnik,župni_ured,adresa,misa+,god_osnutka?,max_kapacitet?,aktivnost*,zbor?)>
<!ATTLIST crkva kategorija (katolička|pravoslavna|protestantska) #REQUIRED>
<!ATTLIST crkva id ID #REQUIRED>
<!-- naziv -->
<!ELEMENT naziv (#PCDATA)>
<!ATTLIST naziv eng CDATA #IMPLIED>
<!--župnik-->
<!ELEMENT župnik (ime,prezime,telefon*)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ATTLIST telefon tip (mobilni|fiksni|telefaks) #IMPLIED>
<!ATTLIST telefon br_mreze (099|098|095|092|091|0) #REQUIRED>
<!-- župni_ured -->
<!ELEMENT župni_ured (mail?,zu_telefon)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT zu_telefon (#PCDATA)>
<!ATTLIST zu_telefon tip (mobilni|fiksni|telefaks) #IMPLIED>
<!ATTLIST zu_telefon br_mreze (099|098|095|092|091|0) #REQUIRED>

<!-- adresa -->
<!ELEMENT adresa (mjesto,ulica?)>
<!ELEMENT mjesto (#PCDATA)>
<!ATTLIST mjesto pos_broj CDATA #REQUIRED>
<!ELEMENT ulica (#PCDATA)>
<!ATTLIST ulica kuc_broj CDATA #IMPLIED>
<!--misa-->
<!ELEMENT misa (vrijeme)>
<!ATTLIST misa dan_u_tjednu (Ponedjeljak|Utorak|Srijeda|Četvrtak|Petak|Subota|Nedjelja) #REQUIRED>
<!ATTLIST misa ispovijed (Prije|Poslije) #IMPLIED>
<!ELEMENT vrijeme (#PCDATA)>
<!-- god_osnutka -->
<!ELEMENT god_osnutka (#PCDATA)>
<!-- max_kapacitet -->
<!ELEMENT max_kapacitet (#PCDATA)>
<!-- aktivnost -->
<!ELEMENT aktivnost EMPTY>
<!ATTLIST aktivnost naziv (Vjeronauk|Zaruke|Ministriranje|Caritas) #REQUIRED>
<!-- zbor -->
<!ELEMENT zbor (zbor_naziv,broj?)>
<!ELEMENT zbor_naziv (#PCDATA)>
<!ELEMENT broj (#PCDATA)>

=== tonyprod97/Open_Computing-6th_semester/laboratory/Open_Computing-6th_semester/podaci.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE podaci SYSTEM "./gramatika.dtd">
<?xml-stylesheet type="text/xsl" href="./pretvorba.xsl"?>
<podaci>
    
<crkva kategorija="katolička">
    <naziv>Zagrebačka katedrala</naziv>
    <župnik>
        <ime>Ivan</ime>
        <prezime>Ivanić</prezime>
        <telefon tip="mobilni" br_mreze="099">9998989</telefon>
        <telefon tip="mobilni" br_mreze="0">12453453</telefon>
    </župnik>
    <župni_ured>
        <mail>tiskovni@zg-nadbiskupija.hr</mail>
        <zu_telefon tip="fiksni" br_mreze="0">14894878</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
        <ulica kuc_broj="31">Kaptol</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak" ispovijed="Prije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Subota" ispovijed="Prije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1094</god_osnutka>
    <max_kapacitet>1500</max_kapacitet>
  <aktivnost naziv="Vjeronauk"/>
  <aktivnost naziv="Zaruke"/>
    <zbor>
        <zbor_naziv>Slavuji Katedrale Zagreb</zbor_naziv>
    </zbor>
</crkva>
<crkva kategorija="katolička">
    <naziv>Dubrovačka katedrala</naziv>
    <župnik>
        <ime>Vlaho</ime>
        <prezime>Katušić</prezime>
        <telefon tip="mobilni" br_mreze="091">8798529</telefon>
        <telefon tip="mobilni" br_mreze="092">8709229</telefon>
    </župnik>
    <župni_ured>
        <mail>dubrovnik.katedrala@info.hr</mail>
        <zu_telefon tip="fiksni" br_mreze="0">20312011</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="20000">Dubrovnik</mjesto>
        <ulica kuc_broj="5">Brsalje</ulica>
    </adresa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Petak" ispovijed="Prije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Ponedjeljak" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <max_kapacitet>500</max_kapacitet>
  <aktivnost naziv="Vjeronauk"/>
  <aktivnost naziv="Caritas"/>
  <aktivnost naziv="Ministriranje"/>
      <zbor>
        <zbor_naziv>
            Zbor sv. Vlaha
            </zbor_naziv>
    </zbor>
</crkva>
<crkva kategorija="katolička" >
       <!-- naziv je jednak naslovu na wiki-->
    <naziv>Katedrala Svetog Vida u Rijeci</naziv>
    <župnik>
        <ime>Mihovil</ime>
        <prezime>Radić</prezime>
        <telefon tip="mobilni" br_mreze="092">14568875</telefon>
    </župnik>
    <župni_ured>
        <mail>zupa-vido@email.t-com.hr</mail>
        <zu_telefon tip="mobilni" br_mreze="099">87952365</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="51000">Rijeka</mjesto>
        <ulica kuc_broj="2">Trg Svete Barbare</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Petak" ispovijed="Prije">
        <vrijeme>19:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1638</god_osnutka>
    <max_kapacitet>300</max_kapacitet>
  <aktivnost naziv="Zaruke"/>
    <zbor>
        <zbor_naziv>
            Vidova Dica
            </zbor_naziv>
            <broj>27</broj>
    </zbor>
</crkva>
<crkva kategorija="pravoslavna">
  <!-- naziv je jednak naslovu na wiki-->
  <naziv>Saborna crkva Preobraženja Gospodnjeg u Zagrebu</naziv>
    <župnik>
        <ime>Bogdan</ime>
        <prezime>Malik</prezime>
        <telefon tip="mobilni" br_mreze="098">9479100</telefon>
    </župnik>
    <župni_ured>
        <zu_telefon tip="fiksni" br_mreze="0">14614132</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
    </adresa>
  <misa dan_u_tjednu="Utorak">
    <vrijeme>06:00</vrijeme>
  </misa>
    <misa dan_u_tjednu="Srijeda">
        <vrijeme>17:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Petak">
        <vrijeme>10:00</vrijeme>
    </misa>
    <god_osnutka>1866</god_osnutka>
    <max_kapacitet>70</max_kapacitet>
</crkva>
<crkva kategorija="pravoslavna">
     <!-- naziv je jednak naslovu na wiki-->
    <naziv>Pravoslavna crkva sv. Trojice u Bjelovaru</naziv>
    <župnik>
        <ime>Nast</ime>
        <prezime>Rojić</prezime>
        <telefon tip="mobilni" br_mreze="098">8971523</telefon>
    </župnik>
    <župni_ured>
        <zu_telefon tip="fiksni" br_mreze="0">14614132</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="43000">Bjelovar</mjesto>
        <ulica kuc_broj="8">Ulica Ljudevita Gaja</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak">
        <vrijeme>06:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Utorak">
        <vrijeme>17:00</vrijeme>
    </misa>
    <god_osnutka>1793</god_osnutka>
    <max_kapacitet>150</max_kapacitet>
  <aktivnost naziv="Caritas"/>
</crkva>
<crkva kategorija="katolička">
    <naziv>crkva Gospe od Betlema</naziv>
    <župnik>
        <ime>Marko</ime>
        <prezime>Šoltarić</prezime>
        <telefon tip="mobilni" br_mreze="098">8571289</telefon>
    </župnik>
    <župni_ured>
        <mail>zupni-ured@sveti-petar.hr</mail>
        <zu_telefon tip="fiksni" br_mreze="0">14633534</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="21000">Split</mjesto>
        <ulica kuc_broj="3">Marangunićevo šetalište</ulica>
    </adresa>
    <misa dan_u_tjednu="Petak" ispovijed="Poslije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Subota" ispovijed="Poslije">
        <vrijeme>19:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Poslije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <god_osnutka>1500</god_osnutka>
</crkva>
<crkva kategorija="katolička">
    <naziv>Svetoga križa Zagreb</naziv>
    <župnik>
        <ime>Marko</ime>
        <prezime>Matelj</prezime>
        <telefon tip="mobilni" br_mreze="0">12432453</telefon>
    </župnik>
    <župni_ured>
        <mail>svKriža@biskupija.hr</mail>
        <zu_telefon tip="fiksni" br_mreze="0">14821878</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
        <ulica kuc_broj="21">Sv.Križa</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak" ispovijed="Prije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Subota" ispovijed="Prije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1094</god_osnutka>
    <max_kapacitet>1500</max_kapacitet>
  <aktivnost naziv="Vjeronauk"/>
  <aktivnost naziv="Zaruke"/>
</crkva>
<crkva kategorija="katolička">
    <naziv>Crkva Bogdana Mandića</naziv>
    <župnik>
        <ime>Branimir</ime>
        <prezime>Pan</prezime>
        <telefon tip="mobilni" br_mreze="099">99912389</telefon>
        <telefon tip="mobilni" br_mreze="0">12453453</telefon>
    </župnik>
    <župni_ured>
        <zu_telefon tip="fiksni" br_mreze="0">14894878</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
        <ulica kuc_broj="2">Dankovečka</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak" ispovijed="Prije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Subota" ispovijed="Prije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1094</god_osnutka>
    <max_kapacitet>1500</max_kapacitet>
  <aktivnost naziv="Vjeronauk"/>
  <aktivnost naziv="Caritas"/>
</crkva>
</podaci>

=== tonyprod97/Open_Computing-6th_semester/laboratory/Open_Computing-6th_semester/data/podaci.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE podaci SYSTEM "./gramatika.dtd">
<?xml-stylesheet type="text/xsl" href="./pretvorba.xsl"?>
<podaci>
    
<crkva kategorija="katolička" aktivnosti="Ministriranje Zaruke">
    <naziv>Zagrebačka katedrala</naziv>
    <župnik>
        <ime>Ivan</ime>
        <prezime>Ivanić</prezime>
        <telefon tip="mobilni" br_mreze="099">9998989</telefon>
    </župnik>
    <župni_ured>
        <mail>tiskovni@zg-nadbiskupija.hr</mail>
        <zu_telefon tip="fiksni" br_mreze="0">14894878</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
        <ulica kuc_broj="31">Kaptol</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak" ispovijed="Prije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Subota" ispovijed="Prije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1094</god_osnutka>
    <max_kapacitet>1500</max_kapacitet>
    <zbor>
        <zbor_naziv>Slavuji Katedrale Zagreb</zbor_naziv>
    </zbor>
</crkva>
<crkva kategorija="katolička" aktivnosti="Zaruke Vjeronauk">
    <naziv>Dubrovačka katedrala</naziv>
    <župnik>
        <ime>Vlaho</ime>
        <prezime>Katušić</prezime>
        <telefon tip="mobilni" br_mreze="091">8798529</telefon>
    </župnik>
    <župni_ured>
        <mail>dubrovnik.katedrala@info.hr</mail>
        <zu_telefon tip="fiksni" br_mreze="0">20312011</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="20000">Dubrovnik</mjesto>
        <ulica kuc_broj="5">Brsalje</ulica>
    </adresa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Petak" ispovijed="Prije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Ponedjeljak" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <max_kapacitet>500</max_kapacitet>
      <zbor>
        <zbor_naziv>
            Zbor sv. Vlaha
            </zbor_naziv>
    </zbor>
</crkva>
<crkva kategorija="katolička" aktivnosti="Caritas Vjeronauk Zaruke">
    <naziv>Katedrala Svetog Vida</naziv>
    <župnik>
        <ime>Mihovil</ime>
        <prezime>Radić</prezime>
        <telefon tip="mobilni" br_mreze="092">14568875</telefon>
    </župnik>
    <župni_ured>
        <mail>zupa-vido@email.t-com.hr</mail>
        <zu_telefon tip="mobilni" br_mreze="099">87952365</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="51000">Rijeka</mjesto>
        <ulica kuc_broj="2">Trg Svete Barbare</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Petak" ispovijed="Prije">
        <vrijeme>19:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Prije">
        <vrijeme>11:00</vrijeme>
    </misa>
    <god_osnutka>1638</god_osnutka>
    <max_kapacitet>300</max_kapacitet>
    <zbor>
        <zbor_naziv>
            Vidova Dica
            </zbor_naziv>
            <broj>27</broj>
    </zbor>
</crkva>
<crkva kategorija="pravoslavna">
    <naziv>Preobraženja gospodnjeg</naziv>
    <župnik>
        <ime>Bogdan</ime>
        <prezime>Malik</prezime>
        <telefon tip="mobilni" br_mreze="098">9479100</telefon>
    </župnik>
    <župni_ured>
        <zu_telefon tip="fiksni" br_mreze="0">14614132</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="10000">Zagreb</mjesto>
    </adresa>
  <misa dan_u_tjednu="Utorak">
    <vrijeme>06:00</vrijeme>
  </misa>
    <misa dan_u_tjednu="Srijeda">
        <vrijeme>17:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Petak">
        <vrijeme>10:00</vrijeme>
    </misa>
    <god_osnutka>1866</god_osnutka>
    <max_kapacitet>100</max_kapacitet>
</crkva>
<crkva kategorija="pravoslavna">
    <naziv>Crkva sv. Trojice</naziv>
    <župnik>
        <ime>Nast</ime>
        <prezime>Rojić</prezime>
        <telefon tip="mobilni" br_mreze="098">8971523</telefon>
    </župnik>
    <župni_ured>
        <zu_telefon tip="fiksni" br_mreze="0">14614132</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="43000">Bjelovar</mjesto>
        <ulica kuc_broj="8">Ulica Ljudevita Gaja</ulica>
    </adresa>
    <misa dan_u_tjednu="Ponedjeljak">
        <vrijeme>06:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Utorak">
        <vrijeme>17:00</vrijeme>
    </misa>
    <god_osnutka>1793</god_osnutka>
    <max_kapacitet>150</max_kapacitet>
</crkva>
<crkva kategorija="katolička" aktivnosti="Vjeronauk Zaruke">
    <naziv>Crkva Gospe od Betlema</naziv>
    <župnik>
        <ime>Marko</ime>
        <prezime>Šoltarić</prezime>
        <telefon tip="mobilni" br_mreze="098">8571289</telefon>
    </župnik>
    <župni_ured>
        <mail>zupni-ured@sveti-petar.hr</mail>
        <zu_telefon tip="fiksni" br_mreze="0">14633534</zu_telefon>
    </župni_ured>
    <adresa>
        <mjesto pos_broj="21000">Split</mjesto>
        <ulica kuc_broj="3">Marangunićevo šetalište</ulica>
    </adresa>
    <misa dan_u_tjednu="Petak" ispovijed="Poslije">
        <vrijeme>08:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Subota" ispovijed="Poslije">
        <vrijeme>19:00</vrijeme>
    </misa>
    <misa dan_u_tjednu="Nedjelja" ispovijed="Poslije">
        <vrijeme>18:00</vrijeme>
    </misa>
    <god_osnutka>1500</god_osnutka>
</crkva>
</podaci>
